name       : cawbird
version    : 1.4.1
release    : 12
source     :
    - https://github.com/IBBoard/cawbird/archive/refs/tags/v1.4.1.tar.gz : c527a07d447d189852582bbaff5e6d0d1e432b4b643e8a1703656bab25d31582
homepage   : https://ibboard.co.uk/cawbird/
license    : GPL-3.0-or-later
component  : network.clients
summary    : GTK Twitter client
description: |
    A fork of the Corebird GTK Twitter client that continues to work with Twitter.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %meson_configure \
        -Dconsumer_key_base64=VmY5dG9yRFcyWk93MzJEZmhVdEk5Y3NMOA== \
        -Dconsumer_secret_base64=MThCRXIxbWRESDQ2Y0podzVtVU13SGUyVGlCRXhPb3BFRHhGYlB6ZkpybG5GdXZaSjI=
build      : |
    %ninja_build
install    : |
    %ninja_install
