name       : cawbird
version    : 1.3.1
release    : 10
source     :
    - https://github.com/IBBoard/cawbird/archive/v1.3.1.tar.gz : ec01f14dcc914a27e1e467813dc0d85eaa3916e94865e6f9ce37abec2f036240
homepage   : https://ibboard.co.uk/cawbird/
license    : GPL-3.0-or-later
component  : network.clients
summary    : GTK Twitter client
description: |
    A fork of the Corebird GTK Twitter client that continues to work with Twitter
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
