name       : cawbird
version    : 1.2.1
release    : 8
source     :
    - https://github.com/IBBoard/cawbird/archive/v1.2.1.tar.gz : 38f6a64a92af0e1337c23c285b41167986cb9344cdd6e04b7decd6ce8362bc58
homepage   : https://ibboard.co.uk/cawbird/
license    : GPL-3.0-or-later
component  : network.clients
summary    : GTK Twitter client
description: |
    A fork of the Corebird GTK Twitter client that continues to work with Twitter
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
