name       : cawbird
version    : 1.0.3.1
release    : 3
source     :
    - https://github.com/IBBoard/cawbird/archive/v1.0.3.1.tar.gz : 674fc8550fb978ee5dcff250fa5e81d1017d20d0a7f9a39d557bff3a6aec9b0a
license    : GPL-3.0-or-later
component  : network.clients
summary    : GTK Twitter client
description: |
    A fork of the Corebird GTK Twitter client that continues to work with Twitter
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
