name       : cawbird
version    : 1.0.5
release    : 5
source     :
    - https://github.com/IBBoard/cawbird/archive/v1.0.5.tar.gz : bdbb9baa4e2555e20bc46dc37c9627842fe1b53bd0d70520f9ab5636024204dc
homepage   : https://ibboard.co.uk/cawbird/
license    : GPL-3.0-or-later
component  : network.clients
summary    : GTK Twitter client
description: |
    A fork of the Corebird GTK Twitter client that continues to work with Twitter
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
